"""add_customer_health_fields_and_billing_table

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-05 14:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6g7"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 添加客户健康度字段到 customers 表
    op.add_column(
        "customers",
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "customers",
        sa.Column("health_score", sa.Integer(), default=50, nullable=False),
    )

    # 2. 创建 billings 表
    op.create_table(
        "billings",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_name", sa.String(255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("completed", "pending", "failed", name="billing_status"),
            nullable=False,
            default="pending",
        ),
        sa.Column("billing_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建索引
    op.create_index(op.f("ix_billings_id"), "billings", ["id"], unique=False)
    op.create_index(
        op.f("ix_billings_customer_id"), "billings", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_billings_status"), "billings", ["status"], unique=False)

    # 4. 创建外键
    op.create_foreign_key(
        "fk_billings_customer_id",
        "billings",
        "customers",
        ["customer_id"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 删除外键
    op.drop_constraint("fk_billings_customer_id", "billings", type_="foreignkey")

    # 2. 删除索引
    op.drop_index(op.f("ix_billings_status"), table_name="billings")
    op.drop_index(op.f("ix_billings_customer_id"), table_name="billings")
    op.drop_index(op.f("ix_billings_id"), table_name="billings")

    # 3. 删除 billings 表
    op.drop_table("billings")

    # 4. 删除客户健康度字段
    op.drop_column("customers", "health_score")
    op.drop_column("customers", "last_active_at")

    # ### end Alembic commands ###
